
name: kbuild

on:
  push:

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        run: sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar gcc-10 g++-10 cmake zstd ninja-build lz4 liblz4-tool liblz4-dev lzma --fix-broken --fix-missing 
      - name: Build Kernel
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          KERNEL_SOURCE: ${{ secrets.KERNEL_SOURCE }}
          ZIP_NAME: ${{ secrets.ZIP_NAME }}
          NAMAKERNEL: ${{ secrets.NAMAKERNEL }}
          HOST: ${{ secrets.HOST }}
          BUILD_USER: ${{ secrets.BUILD_USER }}
          KERNEL_DEFCONFIG: ${{ secrets.KERNEL_DEFCONFIG }}
          DEVICE_CODENAME: ${{ secrets.DEVICE_CODENAME }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ANYKERNEL: ${{ secrets.ANYKERNEL }}
        run: |
          export token=${TG_TOKEN}
          source compile.sh
