name: kbuild

on:
  push:

jobs:
  super-job:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt-mark hold grub-efi-amd64-signed
          sudo apt-get update --fix-missing
          sudo apt-get upgrade
          sudo apt-get install openssh-server screen python python2 python3 git openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev  liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev libtinfo5 libncurses5
          
      - name: Build & Push
        run: |
          git config --global user.name "${GITHUB_USER}"
          git config --global user.email "${GITHUB_EMAIL}"
          source env.sh
          echo "Cloning kernel"
          git clone --depth=1 $KERNEL_REPO -b $KERNEL_BRANCH kernel && cd kernel
          mv /home/runner/work/kbuild/kbuild/bul.sh /home/runner/work/kbuild/kbuild/kernel
          source yaknah.sh

        env:
          GITHUB_EMAIL: ${{ secrets.EMAIL }}
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_USER: ${{ secrets.USERNAME }}
          TG_CHAT_ID: ${{ secrets.CHAT_ID }}
          TG_TOKEN: ${{ secrets.TOKEN }}
          KERNEL_SOURCE: ${{ secrets.KERNEL_SOURCE }}
          KERNEL_DEFCONFIG: ${{ secrets.KERNEL_DEFCONFIG }}
          HOST: ${{ secrets.HOST }}
          BUILD_USER: ${{ secrets.BUILD_USER }}
          ZIPNAME: ${{ secrets.ZIPNAME }}
      - uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.CHAT_ID }} # user id or channel name secret
          token: ${{ secrets.TOKEN }} # token secret
          status: ${{ job.status }} # do not modify this line
